version: "3"
services:
  redis:
    image: redis:7
    env_file: .env
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  collector:
    build: .
    env_file: .env
    environment:
      SERVICE: smartmoney_bot.collector.collector_service
    volumes:
      - ./parquets:/parquets
    depends_on:
      - redis
  metrics:
    build: .
    env_file: .env
    environment:
      SERVICE: smartmoney_bot.metrics.metric_engine
    volumes:
      - ./parquets:/parquets
    depends_on:
      - redis
  orchestrator:
    build: .
    env_file: .env
    environment:
      SERVICE: smartmoney_bot.orchestrator.engine
    depends_on:
      - redis
      - postgres
  prometheus:
    image: prom/prometheus
    env_file: .env
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana-dashboard.json:/etc/grafana/provisioning/dashboard.json
  alertbot:
    build: .
    env_file: .env
    environment:
      SERVICE: smartmoney_bot.alert.alertbot
    depends_on:
      - redis
      - postgres
