name: Export PnL

on:
  schedule:
    - cron: '30 23 * * *'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install asyncpg pandas python-dateutil
      - name: Export PnL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          START=$(date -u -d "yesterday" +%F)
          END=$(date -u +%F)
          python src/ops/export_pnl.py $START $END pnl_$START.csv
          echo "OUT=pnl_$START.csv" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: pnl-${{ env.START }}
          path: ${{ env.OUT }}
